### ISSUE TITLE
Problem running Spark Job with scopt in EMR

### ISSUE THREAD

**Issue by chuwy** [scopt/scopt#103]
My Spark job throwing following runtime exception while running on AWS EMR:

```
java.lang.NoSuchMethodError: scopt.Read$.seqRead(Lscopt/Read;)Lscopt/Read;
        at com.snowplowanalytics.schemaguru.sparkjob.OptionsParserCLI$$anon$1.<init>(OptionsParserCLI.scala:58)
        at com.snowplowanalytics.schemaguru.sparkjob.OptionsParserCLI$.getParser(OptionsParserCLI.scala:43)
        at com.snowplowanalytics.schemaguru.sparkjob.OptionsParserCLI$.parse(OptionsParserCLI.scala:29)
        at com.snowplowanalytics.schemaguru.sparkjob.SchemaDerive$.execute(SchemaDerive.scala:50)
        at com.snowplowanalytics.schemaguru.sparkjob.SchemaDeriveJob$.main(SchemaDeriveJob.scala:22)
        at com.snowplowanalytics.schemaguru.sparkjob.SchemaDeriveJob.main(SchemaDeriveJob.scala)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:606)
        at org.apache.spark.deploy.yarn.ApplicationMaster$$anon$2.run(ApplicationMaster.scala:480)
```

It points to following code snippet:

``` scala
      opt[Seq[String]]("enum-sets") action { (x, c) =>
        c.copy(enumSets=true) } valueName "[<set1>,<set2>,<file1>...|all]"
```

I tried different AMI (3.3, 3.8, 3.9), compiled fatjar with both 2.10 and 2.11 and problem gone only after I removed `Seq` from option. I've seen similar [issue](http://stackoverflow.com/questions/23434393/scala-option-parsing-with-scopt), but can't see how this can be related to my case.

scopt version is 3.4.0. Also it seems run ok on local spark-shell and fails only on EMR.

**Comment by chuwy** [comment]
Nope, problem isn't gone. Running with another `Unit` flag specified.

```
16/03/25 17:48:01 ERROR yarn.ApplicationMaster: User class threw exception: scala.runtime.IntRef.create(I)Lscala/runtime/IntRef;
java.lang.NoSuchMethodError: scala.runtime.IntRef.create(I)Lscala/runtime/IntRef;
        at scopt.OptionParser.parse(options.scala:306)
        at com.snowplowanalytics.schemaguru.sparkjob.OptionsParserCLI$.parse(OptionsParserCLI.scala:30)
        at com.snowplowanalytics.schemaguru.sparkjob.SchemaDerive$.execute(SchemaDerive.scala:50)
        at com.snowplowanalytics.schemaguru.sparkjob.SchemaDeriveJob$.main(SchemaDeriveJob.scala:22)
        at com.snowplowanalytics.schemaguru.sparkjob.SchemaDeriveJob.main(SchemaDeriveJob.scala)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:606)
        at org.apache.spark.deploy.yarn.ApplicationMaster$$anon$2.run(ApplicationMaster.scala:480)
16/03/25 17:48:01 INFO yarn.ApplicationMaster: Final app status: FAILED, exitCode: 15, (reason: User class threw exception: scala.runtime.IntRef.create(I)Lscala/runtime/IntRef;)
```

**Comment by eed3si9n** [comment]
Googled "java.lang.NoSuchMethodError: scala.runtime.IntRef.create" and found a Stackoverflow question that I answered for scopt - http://stackoverflow.com/a/23435585/3827

**Comment by chuwy** [comment]
Yep. I linked that one in first post. However, I can't see how it can be useful for me. You suggest there to use sbt. And I'm already using it. I'm assembling fatjar with latest sbt assembly.

**Comment by eed3si9n** [comment]
Can you confirm the Scala version used by your build is 2.11.x?
[AMI Versions Supported in Amazon EMR Versions 2.x and 3.x](http://docs.aws.amazon.com/ElasticMapReduce/latest/DeveloperGuide/ami-versions-supported.html) says 3.11.0 uses Scala 2.11.1.

**Comment by eed3si9n** [comment]
Also could you copy-paste the relevant portion (`libraryDependencies`) of your `build.sbt`?

**Comment by chuwy** [comment]
I believe there's a [confusion](http://danosipov.com/?p=816) about Scala version on EMR, as its Spark jobs should be compiled against 2.10, despite they state they have 2.11 installed. However, I tried both. 

I also do believe real problem lays somewhere in EMR/AMI, not in scopt. But I'm really curious what is going on. 

My dependencies are look like following: https://github.com/snowplow/schema-guru/blob/master/project/Dependencies.scala with argot replaced by scopt.

**Comment by chuwy** [comment]
I also haven't tried latest AMIs yet. I will let you know if it will change something.

**Comment by chuwy** [comment]
Ok. Currently problem looks like following: It gives above exception for `opt[Seq[String]]` on all AMIs. If I change it to `opt[Unit]` it works, but only on AMI > 3.8. This all looks even weirder, but I double-checked everything with prior cleaning target directories.

**Comment by gna-phetsarath** [comment]
I encountered the same problem using scopt 3.4.0 for Scala 2.11 on AWS EMR 4.4.0. 

Even though I could not find `scopt` in the `hadoop classpath`:

```
hadoop classpath --glob | sed s/:/\\n/g | grep .jar | xargs -n 1 jar tvf | grep scopt
```

Also, I noticed that there was an older version of `scopt` in the path somewhere:

```
[hadoop@ip-10-99-XXX-XXX ~]$ find /usr/lib -name *.jar | grep scopt
/usr/lib/zeppelin/interpreter/flink/scopt_2.10-3.2.0.jar
```

scopt 3.2.0 does not support `scopt.Read$.seqRead` so I guessing it's being included in the hadoop classpath from _somewhere_ by _something_.

To get around this, I used the [maven shade plugin](https://maven.apache.org/plugins/maven-shade-plugin/examples/class-relocation.html) to relocate the scopt classes 

```
</configuration>
...
 <relocations>
        <relocation>
            <pattern>scopt</pattern>
            <shadedPattern>shaded.scopt</shadedPattern>
            <excludes>
            </excludes>
        </relocation>
    </relocations>
</configuration>    
```

This worked for me.

**Comment by chuwy** [comment]
Thank you very much @gna-phetsarath! 
I think this issue can be closed. I hope some one else will find it useful.
