### ISSUE TITLE
making cmd/arg/opt hidden make parsing hang cycling infinitely

### ISSUE THREAD

**Issue by dant3** [scopt/scopt#113]
Stacktrace I can catch is:

```
"main@1" prio=5 tid=0x1 nid=NA runnable
  java.lang.Thread.State: RUNNABLE
      at scala.collection.immutable.List.foreach(List.scala:381)
      at scala.collection.generic.TraversableForwarder$class.foreach(TraversableForwarder.scala:35)
      at scala.collection.mutable.ListBuffer.foreach(ListBuffer.scala:45)
      at scala.collection.TraversableLike$class.filterImpl(TraversableLike.scala:247)
      at scala.collection.TraversableLike$class.filter(TraversableLike.scala:259)
      at scala.collection.AbstractTraversable.filter(Traversable.scala:104)
      at scopt.OptionParser$$anonfun$optionsForRender$1.apply(options.scala:313)
      at scopt.OptionParser$$anonfun$optionsForRender$1.apply(options.scala:311)
      at scala.collection.immutable.List.foreach(List.scala:381)
      at scala.collection.generic.TraversableForwarder$class.foreach(TraversableForwarder.scala:35)
      at scala.collection.mutable.ListBuffer.foreach(ListBuffer.scala:45)
      at scopt.OptionParser.optionsForRender(options.scala:311)
      at scopt.OptionParser.renderTwoColumnsUsage(options.scala:295)
      at scopt.OptionParser.renderUsage(options.scala:284)
      at scopt.OptionParser.usage(options.scala:280)
      at scopt.OptionParser.showUsage(options.scala:275)
      at scopt.OptionParser$$anonfun$16.apply(options.scala:243)
      at scopt.OptionParser$$anonfun$16.apply(options.scala:242)
      at scopt.OptionDef$$anonfun$36.apply(options.scala:541)
      at scopt.OptionDef.applyArgument(options.scala:612)
      at scopt.OptionParser.handleArgument$1(options.scala:397)
      at scopt.OptionParser.parse(options.scala:443)
      at cli.Arguments$.parse(Arguments.scala:19)
      at myapp$.myapp$$runCommand$1(myapp.scala:12)
      at myapp$$anonfun$1.apply$mcV$sp(myapp.scala:17)
      at myapp$$anonfun$1.apply(myapp.scala:17)
      at myapp$$anonfun$1.apply(myapp.scala:17)
      at scala.util.Try$.apply(Try.scala:192)
      at myapp$.main(myapp.scala:17)
      at myapp.main(myapp.scala:-1)
```

P.S. originally I was trying to hide root command to only list their subcommands in the list in order to simplify output of --help

**Comment by tksfz** [comment]
I'm also hitting this on 3.5.0. I have a parser with subcommands. Making even one subcommand hidden triggers this.
