### ISSUE TITLE
Failing tests - fatal error: 're2/re2.h' file not found

### ISSUE THREAD

**Issue by Zejnilovic** [scopt/scopt#259]
Pulled clean branch `scopt4`, ran `sbt test`, got: 

```bash
[error] /Users/absz189/Development/scopt/native/target/scala-2.11/native/lib/optional/re2.cpp:61:10: fatal error: 're2/re2.h' file not found
[error] #include <re2/re2.h>
[error]          ^~~~~~~~~~~
[error] 1 error generated.
[error] java.io.IOException: Cannot run program "node": error=2, No such file or directory
[error]         at java.lang.ProcessBuilder.start(ProcessBuilder.java:1048)
[error]         at org.scalajs.jsenv.ExternalJSEnv$AbstractExtRunner.startVM(ExternalJSEnv.scala:143)
[error]         at org.scalajs.jsenv.ExternalJSEnv$AsyncExtRunner.startExternalJSEnv(ExternalJSEnv.scala:222)
[error]         at org.scalajs.jsenv.ExternalJSEnv$AsyncExtRunner.start(ExternalJSEnv.scala:210)
[error]         at org.scalajs.testadapter.TestAdapter.startManagedRunner(TestAdapter.scala:196)
[error]         at org.scalajs.testadapter.TestAdapter.$anonfun$getRunnerForThread$1(TestAdapter.scala:128)
[error]         at scala.collection.concurrent.TrieMap.getOrElseUpdate(TrieMap.scala:903)
[error]         at org.scalajs.testadapter.TestAdapter.getRunnerForThread(TestAdapter.scala:128)
[error]         at org.scalajs.testadapter.TestAdapter.loadFrameworks(TestAdapter.scala:53)
[error]         at org.scalajs.sbtplugin.ScalaJSPluginInternal$.$anonfun$scalaJSTestFrameworkSettings$1(ScalaJSPluginInternal.scala:1037)
[error]         at scala.Function1.$anonfun$compose$1(Function1.scala:44)
[error]         at sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:40)
[error]         at sbt.std.Transform$$anon$4.work(System.scala:67)
[error]         at sbt.Execute.$anonfun$submit$2(Execute.scala:269)
[error]         at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:16)
[error]         at sbt.Execute.work(Execute.scala:278)
[error]         at sbt.Execute.$anonfun$submit$1(Execute.scala:269)
[error]         at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:178)
[error]         at sbt.CompletionService$$anon$2.call(CompletionService.scala:37)
[error]         at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error]         at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[error]         at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error]         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[error]         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[error]         at java.lang.Thread.run(Thread.java:748)
[error] Caused by: java.io.IOException: error=2, No such file or directory
[error]         at java.lang.UNIXProcess.forkAndExec(Native Method)
[error]         at java.lang.UNIXProcess.<init>(UNIXProcess.java:247)
[error]         at java.lang.ProcessImpl.start(ProcessImpl.java:134)
[error]         at java.lang.ProcessBuilder.start(ProcessBuilder.java:1029)
[error]         at org.scalajs.jsenv.ExternalJSEnv$AbstractExtRunner.startVM(ExternalJSEnv.scala:143)
[error]         at org.scalajs.jsenv.ExternalJSEnv$AsyncExtRunner.startExternalJSEnv(ExternalJSEnv.scala:222)
[error]         at org.scalajs.jsenv.ExternalJSEnv$AsyncExtRunner.start(ExternalJSEnv.scala:210)
[error]         at org.scalajs.testadapter.TestAdapter.startManagedRunner(TestAdapter.scala:196)
[error]         at org.scalajs.testadapter.TestAdapter.$anonfun$getRunnerForThread$1(TestAdapter.scala:128)
[error]         at scala.collection.concurrent.TrieMap.getOrElseUpdate(TrieMap.scala:903)
[error]         at org.scalajs.testadapter.TestAdapter.getRunnerForThread(TestAdapter.scala:128)
[error]         at org.scalajs.testadapter.TestAdapter.loadFrameworks(TestAdapter.scala:53)
[error]         at org.scalajs.sbtplugin.ScalaJSPluginInternal$.$anonfun$scalaJSTestFrameworkSettings$1(ScalaJSPluginInternal.scala:1037)
[error]         at scala.Function1.$anonfun$compose$1(Function1.scala:44)
[error]         at sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:40)
[error]         at sbt.std.Transform$$anon$4.work(System.scala:67)
[error]         at sbt.Execute.$anonfun$submit$2(Execute.scala:269)
[error]         at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:16)
[error]         at sbt.Execute.work(Execute.scala:278)
[error]         at sbt.Execute.$anonfun$submit$1(Execute.scala:269)
[error]         at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:178)
[error]         at sbt.CompletionService$$anon$2.call(CompletionService.scala:37)
[error]         at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error]         at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[error]         at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error]         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[error]         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[error]         at java.lang.Thread.run(Thread.java:748)
[error] java.lang.RuntimeException: Failed to compile native library runtime code.
[error]         at scala.sys.package$.error(package.scala:26)
[error]         at scala.scalanative.build.LLVM$.$anonfun$compileNativelib$5(LLVM.scala:103)
[error]         at scala.scalanative.build.LLVM$.$anonfun$compileNativelib$5$adapted(LLVM.scala:90)
[error]         at scala.collection.parallel.mutable.ParArray$ParArrayIterator.foreach(ParArray.scala:142)
[error]         at scala.collection.parallel.ParIterableLike$Foreach.leaf(ParIterableLike.scala:970)
[error]         at scala.collection.parallel.Task.$anonfun$tryLeaf$1(Tasks.scala:49)
[error]         at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:12)
[error]         at scala.util.control.Breaks$$anon$1.catchBreak(Breaks.scala:63)
[error]         at scala.collection.parallel.Task.tryLeaf(Tasks.scala:52)
[error]         at scala.collection.parallel.Task.tryLeaf$(Tasks.scala:46)
[error]         at scala.collection.parallel.ParIterableLike$Foreach.tryLeaf(ParIterableLike.scala:967)
[error]         at scala.collection.parallel.AdaptiveWorkStealingTasks$WrappedTask.internal(Tasks.scala:166)
[error]         at scala.collection.parallel.AdaptiveWorkStealingTasks$WrappedTask.internal$(Tasks.scala:153)
[error]         at scala.collection.parallel.AdaptiveWorkStealingForkJoinTasks$WrappedTask.internal(Tasks.scala:436)
[error]         at scala.collection.parallel.AdaptiveWorkStealingTasks$WrappedTask.compute(Tasks.scala:146)
[error]         at scala.collection.parallel.AdaptiveWorkStealingTasks$WrappedTask.compute$(Tasks.scala:145)
[error]         at scala.collection.parallel.AdaptiveWorkStealingForkJoinTasks$WrappedTask.compute(Tasks.scala:436)
[error]         at java.util.concurrent.RecursiveAction.exec(RecursiveAction.java:189)
[error]         at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
[error]         at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
[error]         at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
[error]         at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
[error] (scoptJS / Test / loadedTestFrameworks) java.io.IOException: Cannot run program "node": error=2, No such file or directory
[error] (scoptNative / Nativetest / nativeLink) Failed to compile native library runtime code.
[error] Total time: 36 s, completed Aug 5, 2019 8:18:33 AM
```

**Comment by eed3si9n** [comment]
I haven't looked at this yet, but I've seen something similar a while back with Scala Native when Google broke the API of https://github.com/google/re2 and Home Brew pulled the latest.

**Comment by LorenzoMonni** [comment]
Any news on this issue?

**Comment by Zejnilovic** [comment]
> Any news on this issue?

Unfortunately, I was not able to look into it properly yet.

**Comment by avdv** [comment]
It seems you simply do not have re2 installed. If you don't want to build the native library, just skip it...

Otherwise, first follow the instructions here: https://www.scala-native.org/en/v0.3.9-docs/user/setup.html

**Comment by eed3si9n** [comment]
I'm closing this as a general Scala Native issue.
