### ISSUE TITLE
[error] Exception in thread "main" java.lang.NoClassDefFoundError: scala/Serializable

### ISSUE THREAD

**Issue by ritchie46** [scopt/scopt#279]
With different versions of `scala` and `sbt`, this Exception is thrown at runtime. 

`[error] Exception in thread "main" java.lang.NoClassDefFoundError: scala/Serializable` Followed by a long stacktrace. 

```
[error]         at java.lang.ClassLoader.defineClass1(Native Method)
[error]         at java.lang.ClassLoader.defineClass(ClassLoader.java:756)
[error]         at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
[error]         at java.net.URLClassLoader.defineClass(URLClassLoader.java:468)
[error]         at java.net.URLClassLoader.access$100(URLClassLoader.java:74)
[error]         at java.net.URLClassLoader$1.run(URLClassLoader.java:369)
[error]         at java.net.URLClassLoader$1.run(URLClassLoader.java:363)
[error]         at java.security.AccessController.doPrivileged(Native Method)
[error]         at java.net.URLClassLoader.findClass(URLClassLoader.java:362)
[error]         at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
[error]         at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:352)
[error]         at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
[error]         at scopt.platform$PlatformReadInstances$class.calendarRead(PlatformReadInstances.scala:20)
[error]         at scopt.Read$.calendarRead(Read.scala:16)
[error]         at scopt.platform$PlatformReadInstances$class.calendarRead(PlatformReadInstances.scala:18)
[error]         at scopt.Read$.calendarRead(Read.scala:16)
[error]         at scopt.platform$PlatformReadInstances$class.$init$(PlatformReadInstances.scala:27)
```

Java version: javac 1.8.0_232

I am trying to run the Functional DSL as described in the README and it failes at calling 

```
OParser.sequence(
    programName("scopt"),
    head("scopt", "4.x"),
    // option -f, --foo
    opt[Int]('f', "foo")
      .action((x, c) => c.copy(foo = x))
      .text("foo is an integer property"),
    // more options here...
  )
```

**Comment by slandelle** [comment]
Possible unaligned Scala library and scopt cross compiled version?

**Comment by ritchie46** [comment]
Yes, After a long day, I see that I have a version mismatch. Forgot the double percent in the `libraryDependencies`. Nevermind!
