### ISSUE TITLE
NPE in Scala 3 (scopt 4.0.1)

### ISSUE THREAD

**Issue by phdoerfler** [scopt/scopt#323]
Runs just fine with Scala 2.13.6 but NPEs with Scala 3.1.0 (and 3.0.1).

## Error
```
[info] running io.doerfler.Main 
[error] (run-main-2) java.lang.ExceptionInInitializerError
[error] java.lang.ExceptionInInitializerError
[error]         at io.doerfler.Main.main(Main.scala)
[error]         at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[error]         at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[error]         at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[error]         at java.base/java.lang.reflect.Method.invoke(Method.java:566)
[error] Caused by: java.lang.NullPointerException
[error]         at scopt.ORunner$.runParser(ORunner.scala:347)
[error]         at scopt.OParser$.parse(OParser.scala:291)
[error]         at io.doerfler.Main$.<clinit>(Main.scala:22)
[error]         at io.doerfler.Main.main(Main.scala)
[error]         at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[error]         at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[error]         at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[error]         at java.base/java.lang.reflect.Method.invoke(Method.java:566)
[error] stack trace is suppressed; run last Compile / bgRun for the full output
[error] Nonzero exit code: 1
[error] (Compile / run) Nonzero exit code: 1
[error] Total time: 0 s, completed 23 Nov 2021, 09:28:18
```

## Code
```scala
package io.doerfler

import scopt.OParser

object Main extends App {
  val builder = OParser.builder[Config]
  val parser1 = {
    import builder._
    OParser.sequence(
      programName("meep"),
      head("meep", "1.0"),
      opt[String]('i', "script")
        .required()
        .action((x, c) => c.copy(script = x))
        .text("the script to provision with"),
      opt[String]('u', "user")
        .action((x, c) => c.copy(user = x))
        .text("the user, defaults to admin")
    )
  }

  OParser.parse(parser1, args, Config()) match {
    case Some(config: Config) =>
      run(config)
    case _ =>
      // arguments are bad, error message will have been displayed
  }

  def run(cfg: Config) = {
    println(s"Running with config $cfg")
  }
}

case class Config(script: String = ".", user: String = "admin")
```

## build.sbt
```scala
ThisBuild / scalaVersion  := "3.1.0"
ThisBuild / scalacOptions := Seq("-unchecked", "-deprecation", "-language:_", "-encoding", "UTF-8")
libraryDependencies += "com.github.scopt" %% "scopt" % "4.0.1"
```

**Comment by phdoerfler** [comment]
Here's a ready to `sbt run` repo:
https://github.com/phdoerfler/bugs/tree/scopt-323

**Comment by eed3si9n** [comment]
@phdoerfler Thanks for the report.

I don't think you're allowed to use `App` in Scala 3 since that relies on delayed initialization feature.
https://docs.scala-lang.org/scala3/book/methods-main-methods.html

**Comment by phdoerfler** [comment]
Indeed, good catch! Works just fine using `def main(args: Array[String])`
