### ISSUE TITLE
NoClassDefFoundError in scopt(4.0.1)

### ISSUE THREAD

**Issue by moseshu** [scopt/scopt#325]
the scala version is 2.12.10
my code is 

```scala
case class Config(ymd: String = "",  from: Int = -20, to: Int = -1)
import scopt.OParser
val builder = OParser.builder[Config]
val parser= {
programName("scopt"),
    head("test", "4.x"),
    opt[Int]('f', "from")
      .action((x, c) => c.copy(from = x))
      .text("from is int"),
    opt[Int]('t', "to")
      .action((x, c) => c.copy(to = x))
      .text("to is an int")
}
```

the error is 

```scala
Java HotSpot(TM) 64-Bit Server VM warning: Cannot open file /data/log/spark2.4/spark-thriftserver-gc.log due to Permission denied

21/12/07 20:01:15 [main] INFO SignalUtils: Registering signal handler for TERM
21/12/07 20:01:15 [main] INFO SignalUtils: Registering signal handler for HUP
21/12/07 20:01:15 [main] INFO SignalUtils: Registering signal handler for INT
21/12/07 20:01:17 [main] WARN NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
21/12/07 20:01:17 [main] INFO SecurityManager: Changing view acls to: hujunjie01
21/12/07 20:01:17 [main] INFO SecurityManager: Changing modify acls to: hujunjie01
21/12/07 20:01:17 [main] INFO SecurityManager: Changing view acls groups to: 
21/12/07 20:01:17 [main] INFO SecurityManager: Changing modify acls groups to: 
21/12/07 20:01:17 [main] INFO SecurityManager: SecurityManager: authentication disabled; ui acls disabled; users  with view permissions: Set(hujunjie01); groups with view permissions: Set(); users  with modify permissions: Set(hujunjie01); groups with modify permissions: Set()
21/12/07 20:01:18 [main] INFO ApplicationMaster: ApplicationAttemptId: appattempt_1638858596896_45096_000004
21/12/07 20:01:18 [main] INFO ApplicationMaster: Starting the user application in a separate Thread
21/12/07 20:01:18 [main] INFO ApplicationMaster: Waiting for spark context initialization...
21/12/07 20:01:18 [Driver] ERROR ApplicationMaster: User class threw exception: java.lang.NoClassDefFoundError: scopt/OParser$
java.lang.NoClassDefFoundError: scopt/OParser$
	at bcut.SparkMain$.main(SparkMain.scala:37)
	at bcut.SparkMain.main(SparkMain.scala)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.spark.deploy.yarn.ApplicationMaster$$anon$2.run(ApplicationMaster.scala:733)
Caused by: java.lang.ClassNotFoundException: scopt.OParser$
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 7 more
```

I check it many times ,but did't find the problem.so what happend to my code ?

**Comment by eed3si9n** [comment]
I am not familiar with how things are packaged in a Spark job, but is it possible that runtime classpath includes some other version of scopt or just missing scopt JAR entirely? Do you have a way of displaying the runtime classpath of your particular execution?

**Comment by moseshu** [comment]
> 

thank you for your reply ,I found the reason, it's solved
