### ISSUE TITLE
provide a parse variant that returns Either[List[String],C]

### ISSUE THREAD

**Issue by LannyRipple** [scopt/scopt#84]
Currently parse() returns Option[C] and on the None case emits warnings/errors to the STDERR.  This behavior falls down in the face of starting a daemon.  A parse variant (e.g., parseEither) that returned Either[List[String],C] where Left was the warnings/errors and Right the resulting config would give more control over where the errors are displayed.  (In my case I want to emit them to a log file.)  I I suppose I could just override reportWarning/Error, showUsageOnError, and showTryHelp but I've always found it odd that scopt wanted to emit the errors to STDERR in the first place.

Anyway I have this coded up and was going to write tests for it but I keep getting 

> java.lang.StackOverflowError
>   at scala.concurrent.forkjoin.ForkJoinPool.tryAddWorker(ForkJoinPool.java:1678)
>   at scala.concurrent.forkjoin.ForkJoinPool.signalWork(ForkJoinPool.java:1966)
>   at scala.concurrent.forkjoin.ForkJoinPool.tryTerminate(ForkJoinPool.java:2622)

and errors like

> java.security.AccessControlException: access denied ("java.io.FilePermission" "/Users/lanny/work/IdeaProjects/scopt/target/test-reports/MutableParserSpec.xml" "write")
>   at java.security.AccessControlContext.checkPermission(AccessControlContext.java:457)

when doing `sbt clean test` on both my topic and current scopt3 branches.

Has anyone encountered this and know how to fix it?  I've tried JDK7 and 8; file and directory permissions look good; and Google is not my friend.

**Comment by ksilin** [comment]
+1 getting a list of errors in a disjunction on parse failures would be great
